# Generated by Django 2.1.11 on 2020-02-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepost_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='column',
        ),
        migrations.DeleteModel(
            name='ArticleColumn',
        ),
    ]
