# Generated by Django 2.1.11 on 2020-03-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20200315_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='avatar',
            new_name='img',
        ),
    ]
